matrix:
  include:
    - language: python
      python: 3.8
      script:
        - flask db upgrade
    - language: node_js
      node_js: 12
      script:
        - npm run build
        - npm run lint
