"""Remove message column in message

Revision ID: e1a4a790dc2b
Revises: 3afeda818c28
Create Date: 2020-12-12 19:54:13.149056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1a4a790dc2b'
down_revision = '3afeda818c28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'message')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('message', sa.VARCHAR(length=2048), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
