"""Add key table.

Revision ID: ec3f242cddd6
Revises: 3f0df7be82df
Create Date: 2020-12-12 14:51:09.128093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec3f242cddd6'
down_revision = '3f0df7be82df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('key',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public', sa.String(length=2048), nullable=True),
    sa.Column('private', sa.String(length=2048), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('key')
    # ### end Alembic commands ###
