"""Add message column in message in binary form

Revision ID: f2d399f00ffd
Revises: e1a4a790dc2b
Create Date: 2020-12-12 19:55:19.072127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2d399f00ffd'
down_revision = 'e1a4a790dc2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('message', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'message')
    # ### end Alembic commands ###
