"""Add user_id column to key table.

Revision ID: fa74b0aaaf93
Revises: ec3f242cddd6
Create Date: 2020-12-12 15:16:24.271800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa74b0aaaf93'
down_revision = 'ec3f242cddd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('key', sa.Column('user_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('key', 'user_id')
    # ### end Alembic commands ###
